# Source: acme/templates/cert-manager-staging-clusterissuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    meta.helm.sh/release-name: 'acme-jx'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "dror@immagnify.com"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsNames:
            - "*.stg.rageofdandelion.pp.ua"
            - "stg.rageofdandelion.pp.ua"
        # ACME DNS-01 provider configurations
        dns01:
          route53:
            region: us-east-2
