apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: Rageofdandelion-STG-EKS
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "657966192050"
    provider: eks
    region: us-east-2
    registry: 657966192050.dkr.ecr.us-east-2.amazonaws.com
  environments:
  - key: dev
    owner: Milakuskus
    repository: jx3-vault
  - key: staging
  - key: production
  ingress:
    domain: stg.rageofdandelion.pp.ua
    externalDNS: true
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: dror@immagnify.com
      enabled: true
      production: false
  pipelineUser:
    username: Milakuskus
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-rageofdandelion-stg-eks-20210916201519166700000006
  - name: reports
    url: s3://reports-rageofdandelion-stg-eks-20210916201519126400000004
  - name: repository
    url: s3://repository-rageofdandelion-stg-eks-20210916201520038000000007
  terraform: true
  vault:
    aws:
      dynamoDBRegion: us-east-2
      dynamoDBTable: vault-unseal-Rageofdandelion-STG-EKS-b97CR2N5
      kmsKeyId: daefcadb-0825-4102-a9cf-470c6d4313ec
      kmsRegion: us-east-2
      s3Bucket: vault-unseal-rageofdandelion-stg-eks-20210916201519126600000005
      s3Region: us-east-2
  webhook: lighthouse
